apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi-deployment
  labels:
    environment: local
    framework: dotnet6
    layer: api
    app: api-weather
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: api-weather
  template:
    metadata:
      labels:
        app: api-weather
    spec:
      containers:
      - name: weatherapi-container
        image: kub-weather-api
        imagePullPolicy: Never
        resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
        ports:
          - containerPort: 80
            # protocol: TCP
        env:
          - name: ASPNETCORE_URLS
            value: http://+80
          - name: REDIS_HOST
            value: cache-service
          - name: REDIS_PORT
            value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: weatherapi-service
  labels:
    app: api-weather
spec:
  type: LoadBalancer
  selector:
    app: api-weather
  ports:
    - port: 6001
      targetPort: 80
      # protocol: TCP
